"""LVQR - Live Video QUIC Relay Python client."""

__version__ = "1.1.0"

from .client import LvqrClient
from .types import (
    # v1.0.0 types
    BroadcastSummary,
    ClusterNodeView,
    ConfigEntry,
    ConfigReloadStatus,
    FederationConnectState,
    FederationLinkStatus,
    FederationStatus,
    MeshPeerStats,
    MeshState,
    NodeCapacity,
    RelayStats,
    SloEntry,
    SloSnapshot,
    StreamInfo,
    StreamKey,
    StreamKeySpec,
    WasmFilterBroadcastStats,
    WasmFilterSlotStats,
    WasmFilterState,
    # v1.1.0 console wave types
    AddAgentRequest,
    AddRenditionRequest,
    AgentActiveStats,
    AgentInfo,
    AgentState,
    ArchiveBroadcastInfo,
    ArchiveState,
    ArchiveTrackInfo,
    BoundAddresses,
    BroadcastSessionInfo,
    BroadcastSessionsState,
    BroadcastStopResult,
    IngestListenerInfo,
    IngestState,
    IngestStopResult,
    LogLine,
    RenditionInfo,
    RuntimeFeatures,
    ServerInfo,
    StreamDetailInfo,
    TrackInfo,
    TranscodeActiveStats,
    TranscodeState,
)

__all__ = [
    "LvqrClient",
    # v1.0.0
    "RelayStats",
    "StreamInfo",
    "StreamKey",
    "StreamKeySpec",
    "ConfigReloadStatus",
    "MeshPeerStats",
    "MeshState",
    "SloEntry",
    "SloSnapshot",
    "NodeCapacity",
    "ClusterNodeView",
    "BroadcastSummary",
    "ConfigEntry",
    "FederationConnectState",
    "FederationLinkStatus",
    "FederationStatus",
    "WasmFilterBroadcastStats",
    "WasmFilterSlotStats",
    "WasmFilterState",
    # v1.1.0 console wave
    "AddAgentRequest",
    "AddRenditionRequest",
    "AgentActiveStats",
    "AgentInfo",
    "AgentState",
    "ArchiveBroadcastInfo",
    "ArchiveState",
    "ArchiveTrackInfo",
    "BoundAddresses",
    "BroadcastSessionInfo",
    "BroadcastSessionsState",
    "BroadcastStopResult",
    "IngestListenerInfo",
    "IngestState",
    "IngestStopResult",
    "LogLine",
    "RenditionInfo",
    "RuntimeFeatures",
    "ServerInfo",
    "StreamDetailInfo",
    "TrackInfo",
    "TranscodeActiveStats",
    "TranscodeState",
]
